/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bihe0832_gradletest_GradleTestDemoNative */

#ifndef _Included_com_bihe0832_gradletest_GradleTestDemoNative
#define _Included_com_bihe0832_gradletest_GradleTestDemoNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bihe0832_gradletest_GradleTestDemoNative
 * Method:    getUpperMD5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bihe0832_gradletest_GradleTestDemoNative_getUpperMD5
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_bihe0832_gradletest_GradleTestDemoNative
 * Method:    getLowerMD5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bihe0832_gradletest_GradleTestDemoNative_getLowerMD5
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
